image: docker

stages:
  - build

.build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t ${CI_REGISTRY_IMAGE}:${IMAGE_TAG} -f ${IMAGE_TAG}.Dockerfile --build-arg DEPLOY_KEY="${DEPLOY_KEY}" .
    - docker push ${CI_REGISTRY_IMAGE}:${IMAGE_TAG}
  services:
    - docker:dind
  only:
    refs:
      - master
      - ci

build php74:
  extends: .build
  variables:
    IMAGE_TAG: php74

build php73:
  extends: .build
  variables:
    IMAGE_TAG: php73

